name: SAuth CI/CD Pipeline

on:
  push:
    branches: [ "main" ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'
      - run: npm ci
    #   - run: npm test

  security-scan:
    needs: test
    runs-on: ubuntu-latest
    permissions:
      security-events: write
    steps:
      - uses: actions/checkout@v4
      - uses: github/codeql-action/init@v3
        with:
          languages: javascript
      - uses: github/codeql-action/analyze@v3

  build-and-push:
    needs: test
    runs-on: ubuntu-latest
    outputs:
      image: ghcr.io/${{ github.repository_owner }}/${{ github.event.repository.name }}:${{ github.sha }}
    steps:
      - uses: actions/checkout@v4
      - uses: docker/setup-buildx-action@v3
      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.CR_PAT }}
      - name: Convert repository name to lowercase
        id: repo
        run: echo "repository=${GITHUB_REPOSITORY,,}" >> $GITHUB_OUTPUT
      - uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: |
            ghcr.io/${{ steps.repo.outputs.repository }}:${{ github.sha }}
            ghcr.io/${{ steps.repo.outputs.repository }}:latest

  deploy:
    needs: [security-scan, build-and-push]
    runs-on: ubuntu-latest
    strategy:
      matrix:
        host: 
          - 'ec2-3-144-128-211.us-east-2.compute.amazonaws.com'
    steps:
      - name: Convert repository name to lowercase
        id: repo
        run: echo "repository=${GITHUB_REPOSITORY,,}" >> $GITHUB_OUTPUT
      - name: Deploy to EC2
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ matrix.host }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_SSH_PRIVATE_KEY }}
          port: 22
          timeout: 300s            # Increased timeout for handshake reliability
          command_timeout: 20m     # Supports longer deploy time if needed
          script_stop: false       # Don't fail immediately if one command fails
          script: |
            sleep $((RANDOM % 10 + 5))
            echo "${{ secrets.CR_PAT }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin
            docker pull ghcr.io/${{ steps.repo.outputs.repository }}:latest
            docker stop sauth-app || true
            docker rm sauth-app || true
            docker run -d -p 3000:3000 --name sauth-app --restart always \
              ghcr.io/${{ steps.repo.outputs.repository }}:latest
            echo "Deployed on ${{ matrix.host }} - http://${{ matrix.host }}:3000"